package com.zrw.playground.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-04T14:58:57.772+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "TestServiceService",
                  wsdlLocation = "http://127.0.0.1:8089/hello?wsdl",
                  targetNamespace = "http://webservice.playground.zrw.com/")
public class TestServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.playground.zrw.com/", "TestServiceService");
    public final static QName TestServicePort = new QName("http://webservice.playground.zrw.com/", "TestServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8089/hello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8089/hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TestService
     */
    @WebEndpoint(name = "TestServicePort")
    public TestService getTestServicePort() {
        return super.getPort(TestServicePort, TestService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestService
     */
    @WebEndpoint(name = "TestServicePort")
    public TestService getTestServicePort(WebServiceFeature... features) {
        return super.getPort(TestServicePort, TestService.class, features);
    }

}
